import { inflateSync } from 'node:zlib';

/**
 * Minimal PDF text extractor for the medication report tests (checkbox 74).
 *
 * The report PDFs are generated by pdf-lib with an embedded subset font: text is
 * written as `<hex> Tj` where the hex is a glyph id, and pdf-lib emits a
 * ToUnicode CMap stream mapping glyph ids back to Unicode. That is exactly the
 * structure this extractor decodes, so a test can assert the *rendered text* of
 * the produced PDF (not just the source strings that fed it). Real-world
 * extraction is additionally proven with pypdf in the task evidence.
 */

function parseToUnicode(cmap: string, map: Map<string, string>): void {
  for (const rawLine of cmap.split(/\r?\n/)) {
    const line = rawLine.trim();
    const bfchar = /^<([0-9A-Fa-f]+)>\s*<([0-9A-Fa-f]+)>/.exec(line);
    if (bfchar) {
      map.set(bfchar[1].toLowerCase(), hexToUnicode(bfchar[2]));
      continue;
    }
    const bfrange = /^<([0-9A-Fa-f]+)>\s*<([0-9A-Fa-f]+)>\s*<([0-9A-Fa-f]+)>/.exec(line);
    if (bfrange) {
      const start = parseInt(bfrange[1], 16);
      const end = parseInt(bfrange[2], 16);
      const target = parseInt(bfrange[3], 16);
      for (let code = start; code <= end; code += 1) {
        map.set(code.toString(16).padStart(bfrange[1].length, '0'), String.fromCodePoint(target + (code - start)));
      }
    }
  }
}

function hexToUnicode(hex: string): string {
  let out = '';
  for (let i = 0; i + 4 <= hex.length; i += 4) {
    const unit = parseInt(hex.slice(i, i + 4), 16);
    if (unit >= 0xd800 && unit <= 0xdbff && i + 8 <= hex.length) {
      const low = parseInt(hex.slice(i + 4, i + 8), 16);
      out += String.fromCodePoint(0x10000 + ((unit - 0xd800) << 10) + (low - 0xdc00));
      i += 4;
    } else {
      out += String.fromCodePoint(unit);
    }
  }
  return out;
}

/** All streams of the PDF, decompressed when FlateDecode is used. */
function readStreams(buf: Buffer): string[] {
  const streams: string[] = [];
  let cursor = 0;
  for (;;) {
    const startMarker = buf.indexOf('stream', cursor);
    if (startMarker < 0) break;
    let start = startMarker + 'stream'.length;
    if (buf[start] === 0x0d) start += 1;
    if (buf[start] === 0x0a) start += 1;
    const endMarker = buf.indexOf('endstream', start);
    if (endMarker < 0) break;
    const chunk = buf.subarray(start, endMarker);
    try {
      streams.push(inflateSync(chunk).toString('latin1'));
    } catch {
      streams.push(chunk.toString('latin1'));
    }
    cursor = endMarker + 'endstream'.length;
  }
  return streams;
}

/** Extract the visible text of a PDF produced by this report renderer. */
export function extractPdfText(pdf: Uint8Array | ArrayBuffer): string {
  const buf = Buffer.from(pdf instanceof ArrayBuffer ? new Uint8Array(pdf) : pdf);
  const streams = readStreams(buf);

  const glyphToUnicode = new Map<string, string>();
  for (const stream of streams) {
    if (stream.includes('beginbfchar') || stream.includes('beginbfrange')) {
      parseToUnicode(stream, glyphToUnicode);
    }
  }

  let text = '';
  for (const stream of streams) {
    if (!stream.includes('Tj') && !stream.includes('TJ')) continue;
    const re = /<([0-9A-Fa-f]+)>\s*Tj/g;
    let match: RegExpExecArray | null;
    while ((match = re.exec(stream)) !== null) {
      const hex = match[1];
      for (let i = 0; i + 4 <= hex.length; i += 4) {
        const code = hex.slice(i, i + 4).toLowerCase();
        text += glyphToUnicode.get(code) ?? '\uFFFD';
      }
      text += '\n';
    }
  }
  return text;
}
