import { randomBytes } from 'crypto';
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';

const ENV_FILE_PATH = join(process.cwd(), 'data', '.env');

interface KeyConfig {
  JWT_SECRET: string;
  MASTER_KEY: string;
}

/**
 * 生成随机密钥
 */
function generateRandomKey(length: number = 64): string {
  return randomBytes(length).toString('hex');
}

/**
 * 从 .env 文件读取配置
 */
function readEnvFile(): Record<string, string> {
  if (!existsSync(ENV_FILE_PATH)) {
    return {};
  }

  const content = readFileSync(ENV_FILE_PATH, 'utf-8');
  const config: Record<string, string> = {};

  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const equalIndex = trimmed.indexOf('=');
    if (equalIndex === -1) continue;

    const key = trimmed.slice(0, equalIndex).trim();
    const value = trimmed.slice(equalIndex + 1).trim();
    config[key] = value;
  }

  return config;
}

/**
 * 保存配置到 .env 文件
 */
function writeEnvFile(config: Record<string, string>): void {
  const dir = dirname(ENV_FILE_PATH);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }

  const lines = [
    '# TimeMark Docker - Auto-generated secrets',
    '# Do not edit this file manually unless you know what you are doing',
    '#',
    `# Generated at: ${new Date().toISOString()}`,
    '',
  ];

  for (const [key, value] of Object.entries(config)) {
    lines.push(`${key}=${value}`);
  }

  writeFileSync(ENV_FILE_PATH, lines.join('\n') + '\n', 'utf-8');
}

/**
 * 初始化密钥配置
 * 首次启动时自动生成随机密钥并保存到 .env 文件
 * 后续启动时从 .env 文件读取已保存的密钥
 */
export function initSecretKeys(): KeyConfig {
  // Vercel 环境：所有密钥来自环境变量，不访问文件系统
  if (process.env.VERCEL) {
    const jwtSecret = process.env.JWT_SECRET;
    const masterKey = process.env.MASTER_KEY;

    if (!jwtSecret || !masterKey) {
      console.error('[secrets] Missing required secrets in Vercel environment');
      console.error('[secrets] Set JWT_SECRET and MASTER_KEY in Vercel Environment Variables');
      throw new Error('JWT_SECRET and MASTER_KEY must be set via Vercel environment variables');
    }

    process.env.JWT_SECRET = jwtSecret;
    process.env.MASTER_KEY = masterKey;

    return { JWT_SECRET: jwtSecret, MASTER_KEY: masterKey };
  }

  // 本地/Docker 环境：从 .env 文件读取，自动生成并保存
  let envConfig = readEnvFile();

  let jwtSecret = process.env.JWT_SECRET || envConfig.JWT_SECRET;
  let masterKey = process.env.MASTER_KEY || envConfig.MASTER_KEY;

  const needsSave = !jwtSecret || !masterKey;

  // 如果没有密钥，自动生成
  if (!jwtSecret) {
    jwtSecret = generateRandomKey(64);
    console.log('🔑 Generated new JWT_SECRET');
  }

  if (!masterKey) {
    masterKey = generateRandomKey(64);
    console.log('🔑 Generated new MASTER_KEY');
  }

  // 保存到 .env 文件
  if (needsSave) {
    envConfig = {
      ...envConfig,
      JWT_SECRET: jwtSecret,
      MASTER_KEY: masterKey,
    };
    writeEnvFile(envConfig);
    console.log('💾 Secrets saved to data/.env');
  } else {
    console.log('🔑 Loaded secrets from data/.env');
  }

  // 设置到环境变量
  process.env.JWT_SECRET = jwtSecret;
  process.env.MASTER_KEY = masterKey;

  return { JWT_SECRET: jwtSecret, MASTER_KEY: masterKey };
}

/**
 * 获取当前密钥配置（用于测试）
 * 必须在 initSecretKeys() 之后调用
 */
export function getSecretKeys(): KeyConfig {
  const jwtSecret = process.env.JWT_SECRET;
  const masterKey = process.env.MASTER_KEY;
  if (!jwtSecret || !masterKey) {
    throw new Error('Secret keys not initialized. Call initSecretKeys() first.');
  }
  return { JWT_SECRET: jwtSecret, MASTER_KEY: masterKey };
}
